### ISSUE TITLE
Refactor `try_seh` to support capturing and forwarding out a return value

### ISSUE THREAD

**Issue by DrChat** [sonodima/microseh#12]
This is fairly trivial to do, here is an example:
```rs
/// Execute a closure inside of a SEH block and return the result.
fn try_seh_rv<T>(f: impl Fn() -> T) -> Result<T, microseh::Exception> {
    let mut rv = MaybeUninit::uninit();
    microseh::try_seh(|| {
        rv.write(f());
    })?;

    // SAFETY: We should only reach this point if the inner closure has returned
    // without throwing an exception, so `rv` should be initialized.
    Ok(unsafe { rv.assume_init() })
}
```

I believe that this change is also non-SemVer breaking, so you can probably avoid cutting a new major release if you change `try_seh`.

**Comment by sonodima** [comment]
This is a good idea, thank you! I wonder if this could be the right moment to add a try_seh! macro that also takes care of this

**Comment by DrChat** [comment]
Oh that is awesome, thank you for making this change so quickly!
