### ISSUE TITLE
Add an ability to retreieve address where the exception happened

### ISSUE THREAD

**Issue by bane9** [sonodima/microseh#3]
Inside the SEH __catch handler, you can retrieve the address of instruction where the exception happened, like so:

```cpp
__try
{
    int x = 0;
    x = 1 / x;
}
__except (EXCEPTION_EXECUTE_HANDLER)
{
    EXCEPTION_POINTERS* pExceptionPointers = GetExceptionInformation();
    EXCEPTION_RECORD* pExceptionRecord = pExceptionPointers->ExceptionRecord;

    DWORD exceptionCode = pExceptionRecord->ExceptionCode;
    PVOID exceptionAddress = pExceptionRecord->ExceptionAddress;
}
```

It would be useful if both `exceptionCode` and  `exceptionAddress` is available from the Rust side

**Comment by sonodima** [comment]
Good suggestion, thank you! I'm going to work on this. 👍🏼

**Comment by sonodima** [comment]
MicroSEH v0.2.0 now includes the exception address!
[crates.io / microseh](https://crates.io/crates/microseh)

**Comment by bane9** [comment]
Thank you 🙂
