### ISSUE TITLE
Possibly fix docs.rs builds

### ISSUE THREAD

**Issue by RivenSkaye** [sonodima/microseh#7]
As docs.rs only compiles on Linux machines and [cross compiles everything else](https://docs.rs/about/builds#cross-compiling) I'm willing to wager the builds would succeed if you changed the capitalization on the include directive to fully lowercase `<windows.h>`.

Windows by default uses case insensitive filesystems, and the cross toolchains all ship lowercased variants of the filename.

**Comment by sonodima** [comment]
Hello, unfortunately even using `windows.h` still results in the [docs build to fail](https://docs.rs/crate/microseh/1.0.1/builds/1120165)

**Comment by sonodima** [comment]
I'm guessing we could probably check if `_WIN32` is defined in `stub.c`, and if it isn't we just export a dummy `HandlerStub` function.

This should work fine because the library is only targeting MSVC anyway.

**Comment by RivenSkaye** [comment]
Oh darn, it tries to build for other targets first. I'll look into ways to convince docs.rs that this crate is really only for windows-msvc targets

**Comment by sonodima** [comment]
Great! Meanwhile I pushed that workaround in the [docs-fix](https://github.com/sonodima/microseh/tree/docs-fix) branch.
If we cannot find other more appropriate fixes, that should do the trick anyway.

**Comment by sonodima** [comment]
Update, v1.0.2 fixes the docs.rs build issue!

**Comment by RivenSkaye** [comment]
Ah, amazing! I'd found [target selection for docs.rs](https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html) which I wanted to try out, but having a working docs build is all that matters here!

**Comment by sonodima** [comment]
> I'd found [target selection for docs.rs](https://blog.rust-lang.org/2020/03/15/docs-rs-opt-into-fewer-targets.html)

That's interesting, I'll take a look at it, maybe we can change that as well!
